version: '3.8'

services:
  gitlab:
    image: gitlab/gitlab-ce:18.8.4-ce.0
    container_name: gitlab-server
    restart: unless-stopped
    hostname: 'localhost'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://localhost:8090'
        # Reducir consumo de memoria para pruebas locales
        postgresql['shared_buffers'] = '256MB'
        sidekiq['max_concurrency'] = 10
        prometheus_monitoring['enable'] = false
    ports:
      - "8090:8090"
      - "2224:22"
    volumes:
      - ./gitlab/config:/etc/gitlab
      - ./gitlab/logs:/var/log/gitlab
      - ./gitlab/data:/var/opt/gitlab
    networks:
      - gitlab-net

  nginx:
    image: nginx:alpine
    container_name: security-reports-web
    restart: unless-stopped
    ports:
      - "8081:80"
    volumes:
      - ./html:/usr/share/nginx/html:ro
    networks:
      - gitlab-net

  gitlab-runner:
    image: gitlab/gitlab-runner:latest
    container_name: gitlab-runner
    restart: unless-stopped
    volumes:
      - ./gitlab-runner/config:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - gitlab-net
    depends_on:
      - gitlab

networks:
  gitlab-net:
    driver: bridge
